//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_auth_data
    {
        public string client_id { get; set; }
        public string sub { get; set; }
        public string auth_code { get; set; }
        public System.DateTime auth_code_date { get; set; }
        public string access_token { get; set; }
        public Nullable<System.DateTime> access_token_date { get; set; }
        public string refresh_token { get; set; }
        public Nullable<System.DateTime> refresh_token_date { get; set; }
        public string nonce { get; set; }
        public string state { get; set; }
        public string code_challenge_method { get; set; }
        public string code_challenge { get; set; }
        public string response_type { get; set; }
        public string response_mode { get; set; }
        public string del_flag { get; set; }
        public System.DateTime regist_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
