//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_client_data
    {
        public string client_id { get; set; }
        public string client_secret { get; set; }
        public string client_name { get; set; }
        public string redirect_uri { get; set; }
        public string transition_uri { get; set; }
        public string scope { get; set; }
        public string del_flag { get; set; }
        public System.DateTime regist_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    }
}
