//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ANSN_SBS_KIYK
    {
        public string ANSN_SBS_KIYK_NO { get; set; }
        public string TYK_YMD { get; set; }
        public string TYS_YMD { get; set; }
        public string KIYK_NO { get; set; }
        public string ANSN_SBS_KIYK_ZYUTI { get; set; }
        public string ANSN_SBS_PRN { get; set; }
        public string ZYUKY_KBN { get; set; }
        public string MSM_YMD { get; set; }
        public string ANSN_SBS_SKMSK_KBN { get; set; }
        public string MUSKMZCTGKIINID { get; set; }
        public string KK_TK_SGYUSY_SSK_NO { get; set; }
        public string KK_TK_SGYUSY_NO { get; set; }
        public string ANSN_SBS_KIYK_KIS_KBN { get; set; }
        public string ANSN_SBS_KIYK_SYRY_KBN { get; set; }
        public string ANSN_SBS_KIYK_RYU { get; set; }
        public string ANSN_SBS_KIYK_BKU { get; set; }
        public string MUSKMZMRMGHISNKBN { get; set; }
        public Nullable<long> ANSN_SBS_SKMSK_NO { get; set; }
        public Nullable<long> ANSN_SBS_KIYK_MSM_NO { get; set; }
        public Nullable<decimal> KUSN_KNTR { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
