//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BIDN
    {
        public string SYB_NO { get; set; }
        public string KIYK_NO { get; set; }
        public string JYDN_CHTN_TKTI_NO { get; set; }
        public string JYDN_BSY { get; set; }
        public string KNY_KKN_CD { get; set; }
        public string KZNO_SM5 { get; set; }
        public string CSV_FILE_MI { get; set; }
        public string YMD { get; set; }
        public Nullable<decimal> BIDN_RYO1 { get; set; }
        public Nullable<decimal> BIDN_RYO2 { get; set; }
        public Nullable<decimal> BIDN_RYO3 { get; set; }
        public Nullable<decimal> BIDN_RYO4 { get; set; }
        public Nullable<decimal> BIDN_RYO5 { get; set; }
        public Nullable<decimal> BIDN_RYO6 { get; set; }
        public Nullable<decimal> BIDN_RYO7 { get; set; }
        public Nullable<decimal> BIDN_RYO8 { get; set; }
        public Nullable<decimal> BIDN_RYO9 { get; set; }
        public Nullable<decimal> BIDN_RYO10 { get; set; }
        public Nullable<decimal> BIDN_RYO11 { get; set; }
        public Nullable<decimal> BIDN_RYO12 { get; set; }
        public Nullable<decimal> BIDN_RYO13 { get; set; }
        public Nullable<decimal> BIDN_RYO14 { get; set; }
        public Nullable<decimal> BIDN_RYO15 { get; set; }
        public Nullable<decimal> BIDN_RYO16 { get; set; }
        public Nullable<decimal> BIDN_RYO17 { get; set; }
        public Nullable<decimal> BIDN_RYO18 { get; set; }
        public Nullable<decimal> BIDN_RYO19 { get; set; }
        public Nullable<decimal> BIDN_RYO20 { get; set; }
        public Nullable<decimal> BIDN_RYO21 { get; set; }
        public Nullable<decimal> BIDN_RYO22 { get; set; }
        public Nullable<decimal> BIDN_RYO23 { get; set; }
        public Nullable<decimal> BIDN_RYO24 { get; set; }
        public Nullable<decimal> BIDN_RYO25 { get; set; }
        public Nullable<decimal> BIDN_RYO26 { get; set; }
        public Nullable<decimal> BIDN_RYO27 { get; set; }
        public Nullable<decimal> BIDN_RYO28 { get; set; }
        public Nullable<decimal> BIDN_RYO29 { get; set; }
        public Nullable<decimal> BIDN_RYO30 { get; set; }
        public Nullable<decimal> BIDN_RYO31 { get; set; }
        public Nullable<decimal> BIDN_RYO32 { get; set; }
        public Nullable<decimal> BIDN_RYO33 { get; set; }
        public Nullable<decimal> BIDN_RYO34 { get; set; }
        public Nullable<decimal> BIDN_RYO35 { get; set; }
        public Nullable<decimal> BIDN_RYO36 { get; set; }
        public Nullable<decimal> BIDN_RYO37 { get; set; }
        public Nullable<decimal> BIDN_RYO38 { get; set; }
        public Nullable<decimal> BIDN_RYO39 { get; set; }
        public Nullable<decimal> BIDN_RYO40 { get; set; }
        public Nullable<decimal> BIDN_RYO41 { get; set; }
        public Nullable<decimal> BIDN_RYO42 { get; set; }
        public Nullable<decimal> BIDN_RYO43 { get; set; }
        public Nullable<decimal> BIDN_RYO44 { get; set; }
        public Nullable<decimal> BIDN_RYO45 { get; set; }
        public Nullable<decimal> BIDN_RYO46 { get; set; }
        public Nullable<decimal> BIDN_RYO47 { get; set; }
        public Nullable<decimal> BIDN_RYO48 { get; set; }
        public string TURKSY_ID { get; set; }
        public string KUSNSY_ID { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
