//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_DNRYK_KYN_HSN
    {
        public string KIYK_NO { get; set; }
        public string KIYK_RNBN { get; set; }
        public string DNRYK_KYN_HSN_RNBN { get; set; }
        public string SISN_FLG { get; set; }
        public Nullable<decimal> JY_KIYK_YURYU { get; set; }
        public string KNSN_KZYN_H { get; set; }
        public string TYUTI_KZYN_H { get; set; }
        public Nullable<decimal> RKRT { get; set; }
        public Nullable<decimal> KUSN_KNTR { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
