//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_DNRYK_TTMSUTWK
    {
        public string DNRYK_TTMS_UTWK_KNR_NO { get; set; }
        public string TTMS_KNR_NO { get; set; }
        public string URAG_YM { get; set; }
        public string SIKYU_KNR_NO { get; set; }
        public string TYUTI_KNR_NO { get; set; }
        public string TYYM { get; set; }
        public string SKTI_NO { get; set; }
        public string KIYK_NO { get; set; }
        public string RYUKN_CD { get; set; }
        public string SBS_CD { get; set; }
        public string DNRYK_HTI_MNY_SYBT { get; set; }
        public string DNRYK_RKUW_CD { get; set; }
        public Nullable<decimal> DNRYK_GK { get; set; }
        public Nullable<decimal> DNRYK_RYU { get; set; }
        public Nullable<decimal> DNRYK_RYU_TNK { get; set; }
        public Nullable<decimal> WRBK_RT { get; set; }
        public string KASN_KBN { get; set; }
        public string SI_KI_KBN { get; set; }
        public string SKM_DRK_TTMS_UW_KNR_NO { get; set; }
        public string UTWKHYUZ_KM_IT { get; set; }
        public string UTWKHYUZ_KM_N { get; set; }
        public string UTWKHYUZ_KM_SN { get; set; }
        public string UTWKHYUZ_KM_YN { get; set; }
        public string UTWKHYUZ_KM_G { get; set; }
        public string RYUKN_TISI_KBN { get; set; }
        public string RYUKN_TISI_YMD { get; set; }
        public Nullable<decimal> KUSN_KNTR { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
