//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_HYUZYU_ZYUSY_MST
    {
        public string TDFK_CD { get; set; }
        public string SKTS_CD { get; set; }
        public string TYK_YMD { get; set; }
        public string TYS_YMD { get; set; }
        public string TDHKSKTSR { get; set; }
        public string TDHKSKTSR_KN { get; set; }
        public string TDFK_HYUZ_ZYN { get; set; }
        public string SKTS_HYUZ_ZYN { get; set; }
        public string SNTKYU_TDFK_ME { get; set; }
        public string SNTKYU_SKTS_ME { get; set; }
        public string ZYUSY_RBR_CD { get; set; }
        public Nullable<decimal> KUSN_KNTR { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
