//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_KIYK_KIYKSY
    {
        public string KIYK_NO { get; set; }
        public string TYK_YMD { get; set; }
        public string KIYK_KIYKSY_RNBN { get; set; }
        public string TYS_YMD { get; set; }
        public string KIYKSY_NO { get; set; }
        public string DKYS_NO { get; set; }
        public string SYKIYK_NO { get; set; }
        public string KIYKSY_KIS_KBN { get; set; }
        public string KIYKSY_SYRY_KBN { get; set; }
        public string HNKU_KIS_KNSN_M { get; set; }
        public string HNKU_SYRY_KNSN_M { get; set; }
        public Nullable<decimal> KUSN_KNTR { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
