//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_KIYK
    {
        public string KIYK_NO { get; set; }
        public string TYK_YMD { get; set; }
        public string TYS_YMD { get; set; }
        public string KIYK_RNBN { get; set; }
        public string SBS_SYBT { get; set; }
        public string KIYK_SYBT { get; set; }
        public string RYSYT { get; set; }
        public string SRID_PTN { get; set; }
        public string KIYK_ZYUTI { get; set; }
        public string TKYK_KIYK_KBN { get; set; }
        public string SKG_NO { get; set; }
        public string KIYK_KNG_H { get; set; }
        public string KIYK_SYRY_YMD { get; set; }
        public string SY_KIYK_NO { get; set; }
        public string SY_KIYK_RNBN { get; set; }
        public string OY_KIYK_NO { get; set; }
        public string OY_KIYK_RNBN { get; set; }
        public string KIYK_KIS_KBN { get; set; }
        public string KIYK_SYRY_KBN { get; set; }
        public Nullable<decimal> KUSN_KNTR { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
