//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MIG
    {
        public string MIG_NO { get; set; }
        public string TYK_YMD { get; set; }
        public string TYS_YMD { get; set; }
        public string MIG_RNBN { get; set; }
        public string MIG_SYBT { get; set; }
        public string SMI_KZ { get; set; }
        public string SMI_KN { get; set; }
        public string KNSKYU_SMI_KN { get; set; }
        public string ZYUSY_NO { get; set; }
        public string SYBZ_DUIT_FLG { get; set; }
        public string SYB_NO { get; set; }
        public Nullable<decimal> KUSN_KNTR { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
