//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MISYP_KNR_MST
    {
        public string SSK_NO { get; set; }
        public string TYK_YMD { get; set; }
        public string TYS_YMD { get; set; }
        public string MSM_KNG_H { get; set; }
        public string MSM_SYRY_YMD { get; set; }
        public string MISYP_ME { get; set; }
        public string ST_YU_MISYP_ME_KN { get; set; }
        public string GSK_CD { get; set; }
        public string HYUZYU_MISYP_YUBN_NO { get; set; }
        public string HYUZYU_MISYP_ZYUSY { get; set; }
        public string HYUZYU_MISYP_DWNO { get; set; }
        public string HYUZYU_MISYP_URL { get; set; }
        public string DKZ_TKTN_UM { get; set; }
        public Nullable<decimal> KUSN_KNTR { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
