//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_RKUW_MST
    {
        public string RYUKN_CD { get; set; }
        public string RKUW_CD { get; set; }
        public string SBS_CD { get; set; }
        public string SBS_SYBT { get; set; }
        public string TYK_YMD { get; set; }
        public string TYS_YMD { get; set; }
        public string RKUW_MS { get; set; }
        public string SISN_TURK_K_FLG { get; set; }
        public string HHC_RKUW_SYYTSY_FLG { get; set; }
        public string SYUYK_RYUKN_CD { get; set; }
        public string SYUYK_RKUW_CD { get; set; }
        public string SYUYKZ_SRYKSNTSY_FLG { get; set; }
        public string MST_KZ_IT { get; set; }
        public string MST_KZ_N { get; set; }
        public string MST_HNKU_RRK { get; set; }
        public Nullable<decimal> KUSN_KNTR { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
