//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SBS_CD_MST
    {
        public string SBS_SYBT { get; set; }
        public string KIYK_SYBT { get; set; }
        public string RYSYT { get; set; }
        public string TYK_YMD { get; set; }
        public string TYS_YMD { get; set; }
        public string SBS_CD { get; set; }
        public string KIYK_SYBT_MS { get; set; }
        public string KIYK_SYBT_MS_TYHY { get; set; }
        public string KSR_BI_YU { get; set; }
        public string KSR_ZYKT { get; set; }
        public string KSR_ZYKT_TYHY { get; set; }
        public string RYSYT_MS { get; set; }
        public string KSR_NZRKT { get; set; }
        public string KSR_NZRKT_TYHY { get; set; }
        public string YKN_KBN { get; set; }
        public string TKBT_YKN_FLG { get; set; }
        public string KIYK_KNR_KBN { get; set; }
        public string KSS_RYNR_FLG { get; set; }
        public string GHP_RYNR_FLG { get; set; }
        public string KIYK_SYKNR_NYURYK_FLG { get; set; }
        public string KRZT_HRI_KNU_FLG { get; set; }
        public string ZN_H_KYUHIZT_YKN_KBN { get; set; }
        public Nullable<decimal> KIYK_KUSN_SYUK { get; set; }
        public string RYOKKT_YMD { get; set; }
        public string RYOKKT_KBN { get; set; }
        public string SGYK_KNSN_GYUM_TK_KBN { get; set; }
        public string SDSYR_KST_FLG { get; set; }
        public string YKSYR_KST_FLG { get; set; }
        public string HRKE_STI_H_STI_KBN { get; set; }
        public string SYSYGKYT_KNU_FLG { get; set; }
        public string TYUK_HWR_KISN_AR_FLG { get; set; }
        public string SSN_NYURYK_YU_FLG { get; set; }
        public string ZKSY_FLG { get; set; }
        public string TKKBT_KISNYU_MKIYK_FLG { get; set; }
        public string KIYK_KUSI_FLG { get; set; }
        public string KIYK_KUSN_SRTS_FLG { get; set; }
        public string NOKGK_YU_FLG { get; set; }
        public string MOK_KISN_YU_FLG { get; set; }
        public string KZN_GKSYR_SKSI_AR_FLG { get; set; }
        public string HHCH_TISYU_YKN_FLG { get; set; }
        public string STYK_KIS_OSRS_SRTS_FLG { get; set; }
        public string TKYK_TAT_TISYU_FLG { get; set; }
        public string KSR_HHC_GMNYU_IT { get; set; }
        public string KSR_HHC_GMNYU_N { get; set; }
        public string KSR_HHC_TYUHYUYU { get; set; }
        public string KYUZT_SSN_NYURYK_FLG { get; set; }
        public string HHC_RK_TISYU_FLG { get; set; }
        public string KIYKHHC_SBS_SYUSI_SYBT { get; set; }
        public string TKYK_GMN_TRTS_FLG { get; set; }
        public string HIS_YKN_YMD { get; set; }
        public string HISZM_FLG { get; set; }
        public string RK_TISYU_FLG { get; set; }
        public string KK_MNT_KIYK_KNU_FLG { get; set; }
        public string RKRT_STI_YU_FLG { get; set; }
        public string ZSK_RKRT_YU_FLG { get; set; }
        public string MST_KZ_IT { get; set; }
        public string MST_KZ_N { get; set; }
        public string MST_HNKU_RRK { get; set; }
        public Nullable<decimal> KUSN_KNTR { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
        public string ANSN_SBS_KIYK_KNU_FLG { get; set; }
    }
}
