//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SHKZ
    {
        public string SHKZ_MSM_KNR_NO { get; set; }
        public string DKYS_NO { get; set; }
        public string SHH_SYU_KNU_FLG { get; set; }
        public string KZNO { get; set; }
        public string TUTYU_NO { get; set; }
        public string MSM_YMD { get; set; }
        public string UKTK_YMD { get; set; }
        public string KUSN_YMD { get; set; }
        public string MSM_SYB_NO { get; set; }
        public string MSM_KIYK_NO { get; set; }
        public string MSM_SKTI_NO { get; set; }
        public string KNYU_SSK_NO { get; set; }
        public string KUHR_UKTK_KBN { get; set; }
        public string KUHR_UKTK_STTS_KBN { get; set; }
        public string YUTY_FLG { get; set; }
        public string TYS_YMD { get; set; }
        public string TYS_RYU_KBN { get; set; }
        public Nullable<decimal> KUSN_KNTR { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
