//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SIKYU_KNR
    {
        public string SIKYU_KNR_NO { get; set; }
        public string SIKYU_YM { get; set; }
        public string URAG_YM { get; set; }
        public string SKTI_NO { get; set; }
        public string SIKYU_TIMNG_KBN { get; set; }
        public string HISN_SIKYU_KBN { get; set; }
        public string SIKYU_KKTI_YMD { get; set; }
        public string URAG_YMD { get; set; }
        public string KSN_YMD { get; set; }
        public string SHKG_YMD { get; set; }
        public string SHH_KBN { get; set; }
        public string KZHK_SKYZT_KBN { get; set; }
        public string KH_DS_YMD_IT { get; set; }
        public string KH_DS_YMD_N { get; set; }
        public string KH_DS_YMD_SN { get; set; }
        public string KZHK_YMD_IT { get; set; }
        public string KZHK_YMD_N { get; set; }
        public string KZHK_YMD_SN { get; set; }
        public string RNZ_KZHK_TURK_YMD { get; set; }
        public string RNZ_KZHK_TRKS_YMD { get; set; }
        public string KRHR_SKYZT_KBN { get; set; }
        public string KRZT_KUH_YMD { get; set; }
        public string KRHR_YMD { get; set; }
        public string RNZ_KRZT_TURK_YMD { get; set; }
        public string RNZ_KRZT_TRKS_YMD { get; set; }
        public string HRIKM_SKYZT_KBN { get; set; }
        public string HKH_SYSK_SYRI { get; set; }
        public string HKH_SYTRYK_YMD { get; set; }
        public string RNZ_HRIKM_TURK_YMD { get; set; }
        public string RNZ_HRIKM_TRKS_YMD { get; set; }
        public string IPN_HRKM_SKYZT_KBN { get; set; }
        public string SKHY_SYTRYK_YMD { get; set; }
        public string TKRI_HUMN_SKYZT_KBN { get; set; }
        public string TKRI_HUMN_SYUKN_YMD { get; set; }
        public string SIKYUSY_ZYUTI_KBN { get; set; }
        public string SIKYUSY_SYSK_SYRI { get; set; }
        public string SIKYUSY_HKU_YMD { get; set; }
        public string RYUKN_TISI_AR_FLG { get; set; }
        public string RYUKN_TISI_YMD { get; set; }
        public string SIKYU_TISI_NIYU_KBN { get; set; }
        public string SIKYU_TISI_YMD { get; set; }
        public string MIG_TYK_YMD { get; set; }
        public string KSB_HNKU_RYU_KBN { get; set; }
        public string KSN_YMD_TISI_YMD { get; set; }
        public string YKGT_KRKS_KBN { get; set; }
        public string KSSYH_ZYUTI_KBN { get; set; }
        public string KSSYH_YTI_YMD { get; set; }
        public string YZNHKH_HKU_ZYUTI_KBN { get; set; }
        public string YZNHKH_HKU_YTI_YMD { get; set; }
        public string KSN_ZYUTI_KBN { get; set; }
        public string KSN_YYK_YMD { get; set; }
        public string KSN_YYK_TRKS_YMD { get; set; }
        public string KSN_KKTI_YMD { get; set; }
        public string SISN_NYUKN_ZYUTI_KBN { get; set; }
        public string SISN_KRNYUKN_ZYUTI_KBN { get; set; }
        public string NYYMD { get; set; }
        public string NKTK_YMD { get; set; }
        public string ZDZT_ZYUTI_KBN { get; set; }
        public string SISN_NYUKN_HUHU_KBN { get; set; }
        public string ZR_EN_SIKYU_FLG { get; set; }
        public string KZHK_IRHK_KNRYU_YMD { get; set; }
        public Nullable<decimal> KUSN_KNTR { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
