//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SKTI_SUHSK
    {
        public string SKTI_NO { get; set; }
        public string TYK_YMD { get; set; }
        public string TYS_YMD { get; set; }
        public string SKTI_SUHSK_RNBN { get; set; }
        public string SESS_KBN { get; set; }
        public string MIG_NO { get; set; }
        public string ZYUSY_NO { get; set; }
        public string SIKYU_SYB_NO { get; set; }
        public string TNKYSK_HMI_FLG { get; set; }
        public Nullable<decimal> KUSN_KNTR { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
