//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SKTI
    {
        public string SKTI_NO { get; set; }
        public string TYK_YMD { get; set; }
        public string TYS_YMD { get; set; }
        public string SKTI_RNBN { get; set; }
        public string DKYS_NO { get; set; }
        public string SHH_NO { get; set; }
        public string SHH_KBN { get; set; }
        public string KZHK_STI_H { get; set; }
        public string KZHK_STI_KIBN { get; set; }
        public string KRHR_STI_H { get; set; }
        public string KRHR_STI_KIBN { get; set; }
        public string HRKE_BNKT_HYUZ_KBN { get; set; }
        public string SYGSK_YKGT_GSN_KYH_FLG { get; set; }
        public string SYSYGKYT_FLG { get; set; }
        public string IDU_TNDK_SIKYU_FLG { get; set; }
        public string SHH_TKYU_YMD { get; set; }
        public string SIKYU_RNBN { get; set; }
        public Nullable<decimal> KUSN_KNTR { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
