//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SYB_HSK
    {
        public string SYB_NO { get; set; }
        public string SYB_HSK_RNBN { get; set; }
        public string SISN_FLG { get; set; }
        public string ZYUSY_NO { get; set; }
        public string SYUSY_MIG_NO { get; set; }
        public string SYB_KYUS_YMD { get; set; }
        public string KYUS_KITI_SYBT { get; set; }
        public string TURK_IDU_KNR_NO { get; set; }
        public string TRKS_IDU_KNR_NO { get; set; }
        public string YUT_DIBNRI_CD { get; set; }
        public string YUT_TYU_SYUBNRI_CD { get; set; }
        public string HIRT_FLG { get; set; }
        public string GSTU_FLG { get; set; }
        public string M_RNTR_AR_FLG { get; set; }
        public string HKU_YUT { get; set; }
        public string GYGS_BNRI { get; set; }
        public string ONRIN_ZN_TKY_FLG { get; set; }
        public Nullable<decimal> KUSN_KNTR { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
