//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SYB_HSK_SYUSI
    {
        public string SYB_NO { get; set; }
        public string TYK_YMD { get; set; }
        public string SYB_HSK_RRK_RNBN { get; set; }
        public string TYS_YMD { get; set; }
        public string SYB_MS_KN { get; set; }
        public string SYB_MS { get; set; }
        public string SYB_ME_STI_AR_FLG { get; set; }
        public Nullable<decimal> KUSN_KNTR { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
