//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SYB_DNRYK_HSK
    {
        public string SYB_NO { get; set; }
        public string SYB_DNRYK_HSK_RNBN { get; set; }
        public string SISN_FLG { get; set; }
        public string KYUKYU_TTN_TKTI_NO { get; set; }
        public string SHIDNJGS_CD { get; set; }
        public string KATIKTJDN_FLG { get; set; }
        public string DNRYK_KBN_IT { get; set; }
        public string DNRYK_MEM_IT { get; set; }
        public string DNRYK_KBN_N { get; set; }
        public string DNRYK_MEM_N { get; set; }
        public string DNRYK_KBN_SN { get; set; }
        public string DNRYK_MEM_SN { get; set; }
        public Nullable<decimal> KUSN_KNTR { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
