//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TK_SBS_JYH
    {
        public string TKJH_KNR_NO { get; set; }
        public decimal TKJH_RRK_RNBN { get; set; }
        public string SSN_FLG { get; set; }
        public string TK_UKTK_YMD { get; set; }
        public string KIYK_NO { get; set; }
        public string SYB_NO { get; set; }
        public string TK_SBS_CD { get; set; }
        public string TK_SBS_KZK_JYKY { get; set; }
        public string TK_SBS_KS_YMD { get; set; }
        public string TK_SBS_SYRY_YMD { get; set; }
        public string TSY_KKNN_YMD { get; set; }
        public string TKS_KKNN_YMD { get; set; }
        public string TK_SBS_SKM { get; set; }
        public string TK_SBS_UKTK_KK { get; set; }
        public string SYK_TSY_KKNN_YMD { get; set; }
        public string SYK_TKS_KKNN_YMD { get; set; }
        public string TSY_KKNN_KK { get; set; }
        public string TKS_KKNN_KK { get; set; }
        public string TRK_YMD { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
