//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TK_SBS_KZK_JYKY_M
    {
        public string TK_SBS_KZK_JYKY { get; set; }
        public string TYK_YMD { get; set; }
        public string TYS_YMD { get; set; }
        public string TK_SBS_KZK_JYKY_BNR { get; set; }
        public string TK_SBS_KZK_JYKY_BNR_MSY { get; set; }
        public string TK_SBS_KZK_JYKY_MSY { get; set; }
        public string TK_SBS_KZK_JYKY_MSY_KY { get; set; }
        public string CLUB_THG_HJTSY_KBN { get; set; }
        public string CLUB_THG_KZK_JYKY_MSY_KY { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
