//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TK_SBS_M
    {
        public string TK_SBS_CD { get; set; }
        public string TYK_YMD { get; set; }
        public string TYS_YMD { get; set; }
        public string TK_KSY_SSK_NO { get; set; }
        public string TK_SBS_MSY { get; set; }
        public string TK_SBS_RYSY { get; set; }
        public string TK_SBS_MSY_HYJY { get; set; }
        public string TK_SBS_MSY_KY { get; set; }
        public string TK_SBS_RYSY_KY { get; set; }
        public Nullable<decimal> TKTN_FY_PNT_SU { get; set; }
        public string SNT_TKTN_FY { get; set; }
        public string TKTN_FYJK { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
