//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TKTN_FYJK_M
    {
        public string TKTN_FYJK { get; set; }
        public string TYK_YMD { get; set; }
        public string TYS_YMD { get; set; }
        public string TKTN_FYJK_BNR { get; set; }
        public string TKTN_FYJK_BNR_MSY { get; set; }
        public string TKTN_FYJK_MSY { get; set; }
        public string TKTN_FYJK_MSY_KY { get; set; }
        public string CLUB_THG_TKTN_FYJK_MSY_KY { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
