//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TTMS
    {
        public string TTMS_KNR_NO { get; set; }
        public string URAG_YM { get; set; }
        public string SIKYU_KNR_NO { get; set; }
        public string TYUTI_KNR_NO { get; set; }
        public string TYYM { get; set; }
        public string SKTI_NO { get; set; }
        public string KIYK_NO { get; set; }
        public Nullable<decimal> GK { get; set; }
        public Nullable<decimal> NYUKN_GK { get; set; }
        public string KSKIB_SYBT { get; set; }
        public string KSKIB { get; set; }
        public string UTWK_KBN { get; set; }
        public string RYUKN_CD { get; set; }
        public string RKUW_CD { get; set; }
        public string SBS_CD { get; set; }
        public string SBS_SYBT { get; set; }
        public string KIYK_SYBT { get; set; }
        public string RYSYT { get; set; }
        public string WRBK_SYBT { get; set; }
        public string YUT_DIBNRI_CD { get; set; }
        public string YUT_TYU_SYUBNRI_CD { get; set; }
        public string SYHZ_KBN { get; set; }
        public Nullable<decimal> SYZR { get; set; }
        public Nullable<decimal> SYHZ { get; set; }
        public string KIYK_RYUKN_KBN { get; set; }
        public string RK_KBN { get; set; }
        public string HWR_KBN { get; set; }
        public string RYUKN_TISI_KBN { get; set; }
        public string RYUKN_TISI_YMD { get; set; }
        public Nullable<decimal> SYR_IT { get; set; }
        public Nullable<decimal> SYR_N { get; set; }
        public string RKH_CD { get; set; }
        public Nullable<decimal> KHN_RYUKN { get; set; }
        public Nullable<decimal> ZRRK_IT { get; set; }
        public Nullable<decimal> ZRRK_N { get; set; }
        public Nullable<decimal> ZRT_IT { get; set; }
        public Nullable<decimal> ZRT_N { get; set; }
        public Nullable<decimal> WRBK_RYUKN { get; set; }
        public Nullable<decimal> WRBK_RT { get; set; }
        public Nullable<decimal> SURYU { get; set; }
        public Nullable<decimal> KISU { get; set; }
        public string SYU_KNG_H { get; set; }
        public string SYU_SYRY_YMD { get; set; }
        public Nullable<decimal> SYU_NSU { get; set; }
        public Nullable<decimal> ZNKI_SSN_T_IT { get; set; }
        public Nullable<decimal> RISKRYU_IT { get; set; }
        public Nullable<decimal> ZNKI_SSN_T_N { get; set; }
        public Nullable<decimal> RISKRYU_N { get; set; }
        public string KZYU_SYBT { get; set; }
        public string SYB_NO { get; set; }
        public string HSIMT_NYYMD { get; set; }
        public string HSIMT_TYYM { get; set; }
        public string TRSBRT_K { get; set; }
        public string SIKYU_KBN { get; set; }
        public string DM_KIYK_FLG { get; set; }
        public string RYUKN_KYUSI_TISI_FLG { get; set; }
        public Nullable<decimal> KUSN_KNTR { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
