//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_WRBK_SBS_CD_MST
    {
        public string SBS_CD { get; set; }
        public string WRBK_SYBT { get; set; }
        public string TYK_YMD { get; set; }
        public string TYS_YMD { get; set; }
        public string KSR_ZYKT { get; set; }
        public string KSR_NZRKT { get; set; }
        public string WSRY_HHC_GMHZY { get; set; }
        public string TYKZGH_TISYU_FLG { get; set; }
        public Nullable<decimal> TYKZGH_SYTRYK_NO { get; set; }
        public string OSRS_MSZ_NO { get; set; }
        public string WRBK_SYBT_MS { get; set; }
        public string WSRY_BI_YU { get; set; }
        public string HIS_YKN_YMD { get; set; }
        public string HISZM_FLG { get; set; }
        public string RK_TISYU_FLG { get; set; }
        public string MST_KZ_IT { get; set; }
        public string MST_KZ_N { get; set; }
        public string MST_HNKU_RRK { get; set; }
        public string ST_WRBK_FLG { get; set; }
        public Nullable<decimal> KUSN_KNTR { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
