//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_YZY_DNRYK_KITR
    {
        public string SYB_NO { get; set; }
        public string KIYK_NO { get; set; }
        public string CSV_FILE_MI { get; set; }
        public string YM { get; set; }
        public int YZY_DNRYK_KITR_RNBN { get; set; }
        public decimal KITR_RYO { get; set; }
        public decimal TNK { get; set; }
        public decimal KITR_GK { get; set; }
        public string TURKSY_ID { get; set; }
        public string KUSNSY_ID { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
