//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ZYUSY
    {
        public string ZYUSY_NO { get; set; }
        public string TYK_YMD { get; set; }
        public string ZYUSY_RNBN { get; set; }
        public string TYS_YMD { get; set; }
        public string YUBN_NO { get; set; }
        public string TDFK_CD { get; set; }
        public string SKTS_CD { get; set; }
        public string GSK_CD { get; set; }
        public string ZYUSY_KN { get; set; }
        public string ZYUSY_KZ { get; set; }
        public string KNSKYU_BNT_KN { get; set; }
        public string TMMTM_KN { get; set; }
        public string TMMTM_KZ { get; set; }
        public string KNSKYU_TMMTM_KN { get; set; }
        public string TMGS_KN { get; set; }
        public Nullable<decimal> KUSN_KNTR { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
