//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_ANSN_SBS_MSKM_UKTK
    {
        public long MSM_NO { get; set; }
        public string MSM_YMD { get; set; }
        public string MSM_KBN { get; set; }
        public string KIYK_NO { get; set; }
        public string ANSN_SBS_KIYK_NO { get; set; }
        public string ANSN_SBS_PLN { get; set; }
        public string MYSHOP_SSK_NO { get; set; }
        public string TM_KBN { get; set; }
        public string KIIN_ID { get; set; }
        public string SGYUSY_CD { get; set; }
        public string SGYUSY_SSK_NO { get; set; }
        public string MSM_KBN_SYUSI { get; set; }
        public string KIYK_MUSKM_RYU { get; set; }
        public string MLMG_HISN_KBN { get; set; }
        public string SGODR_NO { get; set; }
        public string RNKE_KYK_FLG { get; set; }
        public System.DateTime RNKE_KYK_FLG_TIMSTNP { get; set; }
        public string CTG_ERR_IRI_FLG { get; set; }
        public string ERR_CD { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
