//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_ANKT_KK_RRK
    {
        public string KIYK_NO { get; set; }
        public string POINTHY_ID { get; set; }
        public string HY_YM { get; set; }
        public string HY_KY { get; set; }
        public string ANKT_KK { get; set; }
    }
}
