//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_CN_PINT_SYRN
    {
        public string KIIN_ID { get; set; }
        public string SYU_KBN { get; set; }
        public string SYU_YM { get; set; }
        public System.DateTime SYTK_YMD { get; set; }
        public decimal SCN_PINT { get; set; }
        public string SYO_NO { get; set; }
        public string SYO_NAIYO { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
