//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_CN_PINT_ZNDK
    {
        public string KIIN_ID { get; set; }
        public System.DateTime MSM_YMD { get; set; }
        public decimal CN_PINT_ZNDK { get; set; }
        public string LST_CNS_DT { get; set; }
        public string LST_ML_DT { get; set; }
        public string EXP_CNS_DT { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
