//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_CN_PINT_RNKI
    {
        public string KIIN_ID { get; set; }
        public string KIYK_NO { get; set; }
        public string TYUTI_KNR_NO { get; set; }
        public string MSM_YM { get; set; }
        public System.DateTime MSM_YMD { get; set; }
        public string MSM_KBN { get; set; }
        public decimal CNS_PINT { get; set; }
        public Nullable<decimal> SYR_CN { get; set; }
        public Nullable<decimal> SKR_CO { get; set; }
        public decimal CNRG_RT { get; set; }
        public string SYO_NO { get; set; }
        public string SYO_NAIYO { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
        public long SKNSR_ID { get; set; }
    }
}
