//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_CP_PINT_TISY_KIIN
    {
        public string CP_ID { get; set; }
        public int CP_CNT { get; set; }
        public string KIIN_ID { get; set; }
        public string SKTI_NO { get; set; }
        public string TSGS_HYU_FLG { get; set; }
        public string TYK_YM { get; set; }
        public string TYK_YMD { get; set; }
        public string TKY_KKN { get; set; }
        public decimal HY_PINT_SU { get; set; }
        public Nullable<System.DateTime> PINT_HY_YMD { get; set; }
        public string HRY_FLG { get; set; }
        public Nullable<System.DateTime> HRY_YMD { get; set; }
        public string TTY_SYRY_FLG { get; set; }
        public Nullable<System.DateTime> TTY_SYRY_YMD { get; set; }
        public string TURKSY_ID { get; set; }
        public string KUSNSY_ID { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
