//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_CP_PINT_HYUZYU_SYRRK
    {
        public string CP_ID { get; set; }
        public int CP_CNT { get; set; }
        public string KIIN_ID { get; set; }
        public string SYTK_YMD { get; set; }
        public int SYTK_CNT { get; set; }
        public string HYJ_TXT { get; set; }
        public decimal PINT_SU { get; set; }
        public string SIKYU_KNR_NO { get; set; }
        public string TYUTI_KNR_NO { get; set; }
        public string SYTK_SYBT { get; set; }
        public string HHYUZ_FLG { get; set; }
        public string TURKSY_ID { get; set; }
        public string KUSNSY_ID { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
