//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_DNKI_MSKM_COOKIES_JYH
    {
        public string KIIN_ID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public string KI_KIIN_ID { get; set; }
        public string COOKIES_ID { get; set; }
        public string SEIKA_TURK_RESULT { get; set; }
        public string SEIKA_TURK_STATUS_CODE { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
