//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_DNKI_MSKM_UKTK_JYH
    {
        public string KIIN_ID { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public string ENTRY_KIND { get; set; }
        public string NAME1 { get; set; }
        public string NAME2 { get; set; }
        public string KANA1 { get; set; }
        public string KANA2 { get; set; }
        public string TEL_KIND { get; set; }
        public string TEL { get; set; }
        public string ADDR_USE_POST { get; set; }
        public string ADDR_USE1 { get; set; }
        public string ADDR_USE2 { get; set; }
        public string BUILDING_USE { get; set; }
        public string CONTRACT_POWER_COMP { get; set; }
        public string CONTRACT_POWER_COMP2 { get; set; }
        public string CONTRACT_POWER_NUM { get; set; }
        public string SPOT_NUM { get; set; }
        public string CONTRACT_NAME { get; set; }
        public string CONTRACT_KANA { get; set; }
        public string MAIL { get; set; }
        public string CONTRACT_GAS_KIND { get; set; }
        public string CONTRACT_GAS1 { get; set; }
        public string CONTRACT_GAS2 { get; set; }
        public string CONTRACT_GAS_NUM { get; set; }
        public string PLAN { get; set; }
        public string PLAN1_B_UNIT { get; set; }
        public string PLAN1_C_UNIT { get; set; }
        public string PLAN1_LOW_UNIT { get; set; }
        public string PLAN1_S1_UNIT { get; set; }
        public string PLAN1_S2_UNIT { get; set; }
        public string PLAN_DISC1 { get; set; }
        public string PLAN_DISC2 { get; set; }
        public string PLAN_SIMPLE { get; set; }
        public string PLAN_STATE_A { get; set; }
        public string PLAN_STATE_S1 { get; set; }
        public string START_REQ_DATE { get; set; }
        public string PAY { get; set; }
        public string PAY_REQ { get; set; }
        public string DEPUTY_NAME1 { get; set; }
        public string DEPUTY_NAME2 { get; set; }
        public string DEPUTY_KANA1 { get; set; }
        public string DEPUTY_KANA2 { get; set; }
        public string DEPUTY_DEP { get; set; }
        public string DEPUTY_STAFFS_NAME1 { get; set; }
        public string DEPUTY_STAFFS_NAME2 { get; set; }
        public string DEPUTY_TEL { get; set; }
        public string DEPUTY_CONN { get; set; }
        public string DEPUTY_CONN_OTHER { get; set; }
        public string INTRODUCE { get; set; }
        public string DIRECT { get; set; }
        public string DIRECT_CODE { get; set; }
        public string EXTERNAL { get; set; }
        public string EXTERNAL_CODE { get; set; }
        public string TOHO_PERSON { get; set; }
        public string ENTRY_KIND1 { get; set; }
        public string KNPN_CD { get; set; }
        public string PLAN_D { get; set; }
        public string PLAN1_D1_UNIT { get; set; }
        public string PLAN1_D2_UNIT { get; set; }
        public string PLAN_STATE_D1 { get; set; }
        public string KIYKSYO_NO { get; set; }
        public string DNK_WEBMS_MUSKM_FLG { get; set; }
        public string KKNN_ZM_FLG { get; set; }
        public string STATE { get; set; }
        public int SKNSR_ID { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
        public string PLAN_STATE_C { get; set; }
        public string PLAN_STATE_LOW { get; set; }
        public string PLAN_STATE_S2 { get; set; }
    }
}
