//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_ENTR_CD_MST
    {
        public string EVNT_ID { get; set; }
        public string KIJ_ID { get; set; }
        public string ENTR_CD { get; set; }
        public string TRKS_ID { get; set; }
        public string KSNS_ID { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
        public decimal HY_PINT_SU { get; set; }
        public string YUKUKGN_YMD { get; set; }
    }
}
