//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_GIFT_COUPON_LOT_KIIN
    {
        public string KIIN_ID { get; set; }
        public int CP_ID { get; set; }
        public string ML { get; set; }
        public string ML_SB { get; set; }
        public int LOTMAX_CNT { get; set; }
        public int LOTZAN_CNT { get; set; }
        public string AKTSTS_FLG { get; set; }
        public string MOVIESTS_FLG { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
