//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_GIFT_CAMPAIGN_KNRI
    {
        public int CP_ID { get; set; }
        public string SHR_KBN { get; set; }
        public string ML_YTI_SENT_YMD { get; set; }
        public string CPK_YMD { get; set; }
        public string CPS_YMD { get; set; }
        public string ML_HISN_FLG { get; set; }
        public string CP_SBS { get; set; }
        public string AKT_JIS_FLG { get; set; }
        public string AKT_JIS_SBS { get; set; }
        public string MOV_JIS_FLG { get; set; }
        public string MOV_JIS_SBS { get; set; }
        public string CP_CONTENT { get; set; }
        public string CP_CNT_PARAM { get; set; }
        public string ACC_TOKEN { get; set; }
        public string STATUS { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
