//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_GIFT_COUPON_KNRI
    {
        public int CPN_ID { get; set; }
        public int CP_ID { get; set; }
        public string GF_CD_HAKO { get; set; }
        public Nullable<int> WINN_MAX_NUM { get; set; }
        public Nullable<int> ODDS { get; set; }
        public string CPN_CONTENT { get; set; }
        public string HYOJI_KGN { get; set; }
        public Nullable<int> WINN_NUM { get; set; }
        public string RKSN_FLG { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
