//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_GIFT_COUPON_TUSN_KIIN
    {
        public int CP_ID { get; set; }
        public string KIIN_ID { get; set; }
        public int CPN_ID { get; set; }
        public string CPN_PG_URL { get; set; }
        public string YNK_KI { get; set; }
        public string TKT_TIP { get; set; }
        public Nullable<System.DateTime> YUKU_KGN { get; set; }
        public Nullable<System.DateTime> SNTKKGN_KIS_YMD { get; set; }
        public Nullable<System.DateTime> SNTKKGN_SYRY_YMD { get; set; }
        public System.DateTime TUSN_TIMSTNP { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
