//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_KIIN_KIYK_HMTK_OLD
    {
        public string KIIN_ID { get; set; }
        public string KIYK_KISY_CD { get; set; }
        public string SYB_NO { get; set; }
        public string SYB_ZYUSY { get; set; }
        public string KIYK_NO { get; set; }
        public int HMTK_CNT { get; set; }
        public string SBS_SYBT { get; set; }
        public string KIYK_SYBT { get; set; }
        public string MN_KIYK { get; set; }
        public string SKTI_NO { get; set; }
        public string KIYK_SYRY_YMD { get; set; }
        public string HMTK_JYTI { get; set; }
        public Nullable<System.DateTime> HMTK_DT { get; set; }
        public Nullable<System.DateTime> HMTK_KIJY_DT { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
