//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_KIIN_KHN
    {
        public string KIIN_ID { get; set; }
        public string KIIN_SI { get; set; }
        public string KIIN_MI { get; set; }
        public string KIIN_SI_KN { get; set; }
        public string KIIN_MI_KN { get; set; }
        public string KIIN_ML { get; set; }
        public string KIIN_ML_SB { get; set; }
        public string SIBT { get; set; }
        public string SINGP_Y { get; set; }
        public string SINGP_M { get; set; }
        public string SINGP_D { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string ZYUSY_YUBN_NO { get; set; }
        public string ZYUSY_TDFK_CD { get; set; }
        public string ZYUSY_SKTS { get; set; }
        public string ZYUSY_SYBNT { get; set; }
        public string ZYUSY_BLMN { get; set; }
        public string RANK { get; set; }
        public string SMARP_KIIN_CD { get; set; }
        public string SECURTY_CD { get; set; }
        public Nullable<System.DateTime> PWD_SISTI_IRY_TIMSTNP { get; set; }
        public string YUT_KBN { get; set; }
        public Nullable<System.DateTime> YUT_KBN_DT { get; set; }
        public string KMKNSN_HIS_FLG { get; set; }
        public Nullable<System.DateTime> KMKNSN_HIS_FLG_TIMSTNP { get; set; }
        public string KIIN_JYTI { get; set; }
        public string PINT_KIIN_JYTI { get; set; }
        public Nullable<System.DateTime> LIGHT_KIIN_TURK_DT { get; set; }
        public Nullable<System.DateTime> HON_KIIN_TURK_DT { get; set; }
        public Nullable<System.DateTime> PINT_KIIN_NYKI_DT { get; set; }
        public string PINT_HYKH_FLG { get; set; }
        public Nullable<System.DateTime> PINT_HYKH_FLG_TIMSTNP { get; set; }
        public string TIKI_FLG { get; set; }
        public Nullable<System.DateTime> TIKI_FLG_TIMSTNP { get; set; }
        public string RUN_MODE { get; set; }
        public string YB1 { get; set; }
        public string YB2 { get; set; }
        public string YB3 { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
