//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_KIIN_ZYUHU_HNKU_RRK
    {
        public string KIIN_ID { get; set; }
        public System.DateTime HNKU_YMD { get; set; }
        public string KIIN_SI { get; set; }
        public string KIIN_MI { get; set; }
        public string KIIN_SI_KN { get; set; }
        public string KIIN_MI_KN { get; set; }
        public string KIIN_ML { get; set; }
        public string KIIN_ML_SB { get; set; }
        public string SIBT { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string ZYUSY_YUBN_NO { get; set; }
        public string ZYUSY_TDFK_CD { get; set; }
        public string ZYUSY_SKTS { get; set; }
        public string ZYUSY_SYBNT { get; set; }
        public string ZYUSY_BLMN { get; set; }
        public string YUT_KBN { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
