//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_KIIN_KIYK_HMTK_BIDN_20191120
    {
        public string KIIN_ID { get; set; }
        public string SYB_NO { get; set; }
        public string KIYK_NO { get; set; }
        public string JYDN_CHTN_TKTI_NO { get; set; }
        public string HMTK_JYTI { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
