//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_KIIN_UKTK
    {
        public string KIIN_ID { get; set; }
        public string UKTKSY_ID { get; set; }
        public string UKTKSY_SI { get; set; }
        public string UKTKSY_MI { get; set; }
        public string SYZK1 { get; set; }
        public string SYZK2 { get; set; }
        public string KIYK_NO { get; set; }
        public string SYB_NO { get; set; }
        public string HNNN_KKNN_KBN { get; set; }
        public string UKTKSY_MM { get; set; }
        public string DNK_WEBMS_MUSKM_FLG { get; set; }
        public string NNSY_ZM_FLG { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
