//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_KNRSY_MTM_SYR_HMTK
    {
        public string KIIN_ID { get; set; }
        public string KIYK_KISY_CD { get; set; }
        public string SYB_NO { get; set; }
        public string KIYK_NO { get; set; }
        public int HMTK_CNT { get; set; }
        public string SBS_SYBT { get; set; }
        public Nullable<System.DateTime> KNRSY_MTM_SYR_HMTK_DT { get; set; }
        public Nullable<System.DateTime> KNRSY_MTM_SYR_HMTK_KIJY_DT { get; set; }
        public string KNRSY_MTM_SYR_HMTK_KIJY_FLG { get; set; }
        public string TURKSY_ID { get; set; }
        public string KUSNSY_ID { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
