//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_KR_KIIN
    {
        public int KRKIIN_ID { get; set; }
        public string MAIL { get; set; }
        public string SEC_CD { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
    }
}
