//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_LINE_RNKI_JYH
    {
        public int SKNSR_ID { get; set; }
        public string YS_ID { get; set; }
        public string KIIN_ID { get; set; }
        public string RNKI_ZYTI { get; set; }
        public System.DateTime RNKI_TIMSTNP { get; set; }
        public Nullable<System.DateTime> RNKI_KIJY_TIMSTNP { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
