//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_ML_HISN_MST
    {
        public string MLMG_ID { get; set; }
        public string MLMG_NM { get; set; }
        public string FLG_DEFAULT { get; set; }
        public decimal HYZ_ORD { get; set; }
        public System.DateTime TKY_KIS_DT { get; set; }
        public System.DateTime TKY_SYURYO_DT { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public System.DateTime KUSN_TIMSTNP { get; set; }
    }
}
