//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_MTURK_KIIN
    {
        public string MTURK_KIIN_ID { get; set; }
        public string MTURK_PASSWORD { get; set; }
        public string SYB_NO { get; set; }
        public string KIYK_NO { get; set; }
        public string SBS_SYBT { get; set; }
        public string SHH_KBN { get; set; }
        public string KIYKSY_NO { get; set; }
        public string SMI { get; set; }
        public string YUBN_NO { get; set; }
        public string GSK_CD { get; set; }
        public string GSK_MS { get; set; }
        public string ZYUSY { get; set; }
        public string TMMTM { get; set; }
        public string TMGS { get; set; }
        public string YUTO_KB { get; set; }
        public string MTURK_KIIN_HKUKBN { get; set; }
        public string CSV_SYTRYK_FLG { get; set; }
        public System.DateTime YUKUKGN { get; set; }
        public string TURK_ZYUTI_FLG { get; set; }
        public Nullable<System.DateTime> TURK_KNRYU_YMD { get; set; }
        public string TURK_KIIN_ID { get; set; }
        public string TURK_KBN { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
