//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_MTURK_KIIN_YYK
    {
        public string KIYK_NO { get; set; }
        public string ZKB { get; set; }
        public string MTURK_KIIN_HKUKBN { get; set; }
        public string HKZM_KBN { get; set; }
        public string MHK_RY { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
        public Nullable<System.DateTime> MSKM_TIMSTNP { get; set; }
    }
}
