//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_OSRS_INFO
    {
        public int OSRS_ID { get; set; }
        public string KIIN_ID { get; set; }
        public string KIYK_NO { get; set; }
        public string OSRS_KBN { get; set; }
        public string OSRS_TYK_YMD { get; set; }
        public string OSRS_TYS_YMD { get; set; }
        public string OSRS_HJSR_YMD { get; set; }
        public string OSRS_TITLE { get; set; }
        public string OSRS_TEMPLATE { get; set; }
        public string OSRS_PARAMS { get; set; }
        public string ML_SR_FLG { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
