//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_PINT_HYRRK_KIIN
    {
        public string KIIN_ID { get; set; }
        public string POINTHY_ID { get; set; }
        public string HY_YM { get; set; }
        public string HY_KY { get; set; }
        public decimal HY_POINT_CNT { get; set; }
        public System.DateTime HY_TIMSTNP { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
        public long SKNSR_ID { get; set; }
        public string SHOP_TRAN_ID { get; set; }
        public string FORM_ENTRY_ID { get; set; }
        public string VF_STATUS { get; set; }
    }
}
