//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_PINT_ZYT_MSKM
    {
        public string SYHN_KUKN_UKTK_NO { get; set; }
        public string KIIN_ID { get; set; }
        public System.DateTime MSM_YMD { get; set; }
        public string SKTI_NO { get; set; }
        public string KIYK_NO { get; set; }
        public decimal SYU_PINT { get; set; }
        public decimal KUKN_RT { get; set; }
        public decimal ZYT_KNGK { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
