//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_PINT_MST
    {
        public string PINT_HY_ID { get; set; }
        public string PINT_SYBT_CD { get; set; }
        public string PINT_HY_NM { get; set; }
        public decimal HY_PINT_SU { get; set; }
        public string HY_TYPE { get; set; }
        public string MEMO { get; set; }
        public string TURKSY_ID { get; set; }
        public string KUSNSY_ID { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
