//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_PINT_IKTSHY_YMKE
    {
        public string KIIN_ID { get; set; }
        public string TRHK_SYR_YMD { get; set; }
        public string TRHK_SYR_HM { get; set; }
        public string PINT_SYBT_CD { get; set; }
        public string BKU { get; set; }
        public string YMKE_HYJI_MI { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
