//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_RYUKNRNDU_PINT
    {
        public string KIYK_NO { get; set; }
        public string SIKYU_KNR_NO { get; set; }
        public string SIKYU_YM { get; set; }
        public string URAG_YM { get; set; }
        public string SBS_SYBT { get; set; }
        public string SHKG_YMD { get; set; }
        public string KIIN_ID { get; set; }
        public string PINT_HY_ID { get; set; }
        public string PINT_HY_MSG { get; set; }
        public decimal HY_PINT_SU { get; set; }
        public System.DateTime HY_PINT_KISN_DT { get; set; }
        public string CSV_SYTRYK_FLG { get; set; }
        public Nullable<System.DateTime> CSV_SYTRYK_DT { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
