//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_SHK_KIIN_UKTK
    {
        public string KIIN_ID { get; set; }
        public string MAIL { get; set; }
        public string KI_JYH { get; set; }
        public string SGYUSY_ID { get; set; }
        public string DNK_KIYK_FLG { get; set; }
        public string NO_SKBT_FLG { get; set; }
        public string DNK_WEBMS_MUSKM_FLG { get; set; }
        public string KIYK_HMTK_KBN { get; set; }
        public string HMTK_KKNN_ZM_FLG { get; set; }
        public string KIYK_NO { get; set; }
        public string SKS_FY_MKSS_KBN { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
