//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_SKTI_NNSY_OLD1
    {
        public string SKTI_NO { get; set; }
        public string KIIN_ID { get; set; }
        public int SKTI_CNT { get; set; }
        public string SHH_KBN { get; set; }
        public string KZNO_SM4 { get; set; }
        public string NNSY_NO { get; set; }
        public Nullable<System.DateTime> NNSY_NO_DT { get; set; }
        public string NNSY_NO_YUSUSK { get; set; }
        public string NNSY_NO_YUSUSK_YUBN { get; set; }
        public string NNSY_NO_YUSUSK_JYSY { get; set; }
        public string NNSY_ZM_FLG { get; set; }
        public Nullable<System.DateTime> NNSY_TIMSTNP { get; set; }
        public string NNSY_KBN { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
