//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_SNKKIIN_MAIL_UKTK
    {
        public string SSYN_KI { get; set; }
        public string MAIL { get; set; }
        public string KI_JYH { get; set; }
        public string SGYUSY_ID { get; set; }
        public string DNK_KIYK_FLG { get; set; }
        public string NO_SKBT_FLG { get; set; }
        public string KIIN_TURK_KBN { get; set; }
        public string ERR_RY { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
