//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_SRAL_ID
    {
        public string SRAL_ID { get; set; }
        public decimal MNY_ID { get; set; }
        public decimal YUT_KBN { get; set; }
        public string SYHN_KUKN_UKTK_NO { get; set; }
        public decimal SYU_PINT { get; set; }
        public decimal KUKN_RT { get; set; }
        public decimal NBK_KNGK { get; set; }
        public string KIIN_ID { get; set; }
        public System.DateTime HTBN_NTZ { get; set; }
        public System.DateTime YUKUKGN { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
