//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_SYOKAISYA_MST
    {
        public string DIV_CD { get; set; }
        public string DIV_ME { get; set; }
        public string HYZ_DIV_ME { get; set; }
        public string ZYOI_DIV_CD { get; set; }
        public string SYOKAI_SYURUI_CD { get; set; }
        public string SYOKAISYA_SYOZOKU_CD { get; set; }
        public string KIS_LVL_CD { get; set; }
        public string HYZ_FLG { get; set; }
        public decimal HYZ_ORD { get; set; }
        public decimal HYZ_GRP_ORD { get; set; }
        public string HYZ_GRP_ME { get; set; }
        public string KAYI_DIV_NEED_FLG { get; set; }
        public System.DateTime TKY_KIS_DT { get; set; }
        public System.DateTime TKY_SYURYO_DT { get; set; }
        public string TRKS_ID { get; set; }
        public string KSNS_ID { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
