//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_SYOKAISYA_JYOHO
    {
        public string KIIN_ID { get; set; }
        public string SYOKAI_SYURUI_CD { get; set; }
        public string SYOKAISYA_SYOZOKU_CD { get; set; }
        public string DIV_NO_B1 { get; set; }
        public string DIV_NO_B2 { get; set; }
        public string DIV_ME_B1_B2 { get; set; }
        public string TANTOSYA_SI { get; set; }
        public string TANTOSYA_MI { get; set; }
        public System.DateTime TURK_DATE { get; set; }
        public string DAIKO_TOROKU_FLG { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
