//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_SYHN_KUKN_UKTK
    {
        public string SYHN_KUKN_UKTK_NO { get; set; }
        public System.DateTime KUKN_DT { get; set; }
        public string KIIN_CD { get; set; }
        public string SYHN_CD { get; set; }
        public string SYHN_NM { get; set; }
        public string SYHNR { get; set; }
        public string ITEM_ID { get; set; }
        public decimal TYUMN_KSU { get; set; }
        public decimal SYH_PINT { get; set; }
        public string HSSK_SMI_SI { get; set; }
        public string HSSK_SMI_MI { get; set; }
        public string HSSK_SMI_SI_KN { get; set; }
        public string HSSK_SMI_MI_KN { get; set; }
        public string HSSK_TEL { get; set; }
        public string HSSK_ZYUSY_YUBN_NO { get; set; }
        public string HSSK_ZYUSY_TDFK_CD { get; set; }
        public string HSSK_ZYUSY_SKTS { get; set; }
        public string HSSK_ZYUSY_SYBNT { get; set; }
        public string HSSK_ZYUSY_BLMN { get; set; }
        public string SMARP_TRN_ID { get; set; }
        public string MEMO { get; set; }
        public string STATUS { get; set; }
        public string THISY_ID { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
