//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_TIAWS
    {
        public int TIAWS_ID { get; set; }
        public string TIAWS_SYBT_CD { get; set; }
        public string TIAWS_NIY { get; set; }
        public string TIAWS_KIIN_ID { get; set; }
        public string TIAWSSY_SI { get; set; }
        public string TIAWSSY_MI { get; set; }
        public string TIAWSSY_SI_KN { get; set; }
        public string TIAWSSY_MI_KN { get; set; }
        public string TIAWSSY_EMAIL { get; set; }
        public string TIAWSSY_TEL { get; set; }
        public string TIAWSSY_ZYUSY_YUBN_NO { get; set; }
        public string TIAWSSY_ZYUSY_TDFK_CD { get; set; }
        public string TIAWSSY_ZYUSY_SKTS { get; set; }
        public string TIAWSSY_ZYUSY_SYBNT { get; set; }
        public string TIAWSSY_ZYUSY_BLMN { get; set; }
        public Nullable<System.DateTime> TIAWS_TIMSTNP { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
