//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_UKTKSY_KNR
    {
        public string UKTKSY_ID { get; set; }
        public string TYS_YMD { get; set; }
        public string PASSWORD { get; set; }
        public string UKTKSY_SI { get; set; }
        public string UKTKSY_MI { get; set; }
        public string SYZK1 { get; set; }
        public string SYZK2 { get; set; }
        public string TURKSY_ID { get; set; }
        public string KUSNSY_ID { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
