//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_YK_KIYK_MST
    {
        public string KIYK_SYBT { get; set; }
        public string HKIIN_FLG { get; set; }
        public string POINT_KIIN_FLG { get; set; }
        public string YUTO_KB { get; set; }
        public string TURKSY_ID { get; set; }
        public string KUSNSY_ID { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
        public string MTM_SYR_HMTK_FLG { get; set; }
        public string PINT_JYT_FLG { get; set; }
        public string RYKNRYSNY_CP_FLG { get; set; }
        public string RYKNRYSNY_CP_KISN_FLG { get; set; }
        public string DR_HTR_TYS_FLG { get; set; }
    }
}
