//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_YUBN_MST
    {
        public int SEQ_ID { get; set; }
        public string ZNKK_THU_KUKY_DNTI_CD { get; set; }
        public string KYBNO { get; set; }
        public string YBNO { get; set; }
        public string TDFK_MS_KN { get; set; }
        public string SKTS_MS_KN { get; set; }
        public string TYIK_MS_KN { get; set; }
        public string TDFK_MS { get; set; }
        public string SKTS_MS { get; set; }
        public string TYIK_MS { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
