//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TohogasDataContext : DbContext
    {
        public TohogasDataContext()
            : base("name=TohogasDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<a_auth_data> a_auth_data { get; set; }
        public virtual DbSet<a_client_data> a_client_data { get; set; }
        public virtual DbSet<A_LOG> A_LOG { get; set; }
        public virtual DbSet<a_scope_master> a_scope_master { get; set; }
        public virtual DbSet<C_ANSN_SBS_KIYK> C_ANSN_SBS_KIYK { get; set; }
        public virtual DbSet<C_BIDN> C_BIDN { get; set; }
        public virtual DbSet<C_BIDN_20191120> C_BIDN_20191120 { get; set; }
        public virtual DbSet<C_BRK_MST> C_BRK_MST { get; set; }
        public virtual DbSet<C_CD_MST> C_CD_MST { get; set; }
        public virtual DbSet<C_DNRYK_KIYK_MST> C_DNRYK_KIYK_MST { get; set; }
        public virtual DbSet<C_DNRYK_KYN_HSN> C_DNRYK_KYN_HSN { get; set; }
        public virtual DbSet<C_DNRYK_TTMSUTWK> C_DNRYK_TTMSUTWK { get; set; }
        public virtual DbSet<C_DNW> C_DNW { get; set; }
        public virtual DbSet<C_GSK_MST> C_GSK_MST { get; set; }
        public virtual DbSet<C_HYUZYU_ZYUSY_MST> C_HYUZYU_ZYUSY_MST { get; set; }
        public virtual DbSet<C_KIYK> C_KIYK { get; set; }
        public virtual DbSet<C_KIYK_HSK_SYUSI> C_KIYK_HSK_SYUSI { get; set; }
        public virtual DbSet<C_KIYK_KIYKSY> C_KIYK_KIYKSY { get; set; }
        public virtual DbSet<C_KIYK_SKTI> C_KIYK_SKTI { get; set; }
        public virtual DbSet<C_KIYK_SYUSI> C_KIYK_SYUSI { get; set; }
        public virtual DbSet<C_KIYK_WRBK> C_KIYK_WRBK { get; set; }
        public virtual DbSet<C_KIYKSY> C_KIYKSY { get; set; }
        public virtual DbSet<C_KKTZTN_SIKYU> C_KKTZTN_SIKYU { get; set; }
        public virtual DbSet<C_KSYU_M_BT_SYUKI> C_KSYU_M_BT_SYUKI { get; set; }
        public virtual DbSet<C_MIG> C_MIG { get; set; }
        public virtual DbSet<C_MISYP_KNR_MST> C_MISYP_KNR_MST { get; set; }
        public virtual DbSet<C_RKUW_MST> C_RKUW_MST { get; set; }
        public virtual DbSet<C_SBS_CD_MST> C_SBS_CD_MST { get; set; }
        public virtual DbSet<C_SHH> C_SHH { get; set; }
        public virtual DbSet<C_SHKZ> C_SHKZ { get; set; }
        public virtual DbSet<C_SIKYU> C_SIKYU { get; set; }
        public virtual DbSet<C_SIKYU_KNR> C_SIKYU_KNR { get; set; }
        public virtual DbSet<C_SKTI> C_SKTI { get; set; }
        public virtual DbSet<C_SKTI_SUHSK> C_SKTI_SUHSK { get; set; }
        public virtual DbSet<C_SYB> C_SYB { get; set; }
        public virtual DbSet<C_SYB_DNRYK_HSK> C_SYB_DNRYK_HSK { get; set; }
        public virtual DbSet<C_SYB_HSK> C_SYB_HSK { get; set; }
        public virtual DbSet<C_SYB_HSK_SYUSI> C_SYB_HSK_SYUSI { get; set; }
        public virtual DbSet<C_TEKY_MST> C_TEKY_MST { get; set; }
        public virtual DbSet<C_TK_SBS_JYH> C_TK_SBS_JYH { get; set; }
        public virtual DbSet<C_TK_SBS_KZK_JYKY_M> C_TK_SBS_KZK_JYKY_M { get; set; }
        public virtual DbSet<C_TK_SBS_M> C_TK_SBS_M { get; set; }
        public virtual DbSet<C_TKTN_FYJK_M> C_TKTN_FYJK_M { get; set; }
        public virtual DbSet<C_TTMS> C_TTMS { get; set; }
        public virtual DbSet<C_TYUTI> C_TYUTI { get; set; }
        public virtual DbSet<C_WRBK_SBS_CD_MST> C_WRBK_SBS_CD_MST { get; set; }
        public virtual DbSet<C_YZY_DNRYK_KITR> C_YZY_DNRYK_KITR { get; set; }
        public virtual DbSet<C_ZYUSY> C_ZYUSY { get; set; }
        public virtual DbSet<P_AMAZON_ACC_JYH> P_AMAZON_ACC_JYH { get; set; }
        public virtual DbSet<P_ANKT_KK_RRK> P_ANKT_KK_RRK { get; set; }
        public virtual DbSet<P_ANSN_SBS_KIIN_KIYK_HMTK> P_ANSN_SBS_KIIN_KIYK_HMTK { get; set; }
        public virtual DbSet<P_ANSN_SBS_MSKM_UKTK> P_ANSN_SBS_MSKM_UKTK { get; set; }
        public virtual DbSet<P_CD_MST> P_CD_MST { get; set; }
        public virtual DbSet<P_CN_HOYU_MST> P_CN_HOYU_MST { get; set; }
        public virtual DbSet<P_CN_KKRT_MST> P_CN_KKRT_MST { get; set; }
        public virtual DbSet<P_CN_PINT_MSKM> P_CN_PINT_MSKM { get; set; }
        public virtual DbSet<P_CN_PINT_RNKI> P_CN_PINT_RNKI { get; set; }
        public virtual DbSet<P_CN_PINT_SYRN> P_CN_PINT_SYRN { get; set; }
        public virtual DbSet<P_CN_PINT_ZNDK> P_CN_PINT_ZNDK { get; set; }
        public virtual DbSet<P_CN_RGRT_MST> P_CN_RGRT_MST { get; set; }
        public virtual DbSet<P_CN_SYO_MST> P_CN_SYO_MST { get; set; }
        public virtual DbSet<P_CN_TNRT_MST> P_CN_TNRT_MST { get; set; }
        public virtual DbSet<P_CO2_RGRT_MST> P_CO2_RGRT_MST { get; set; }
        public virtual DbSet<P_CP_PINT_HYUZYU_SYRRK> P_CP_PINT_HYUZYU_SYRRK { get; set; }
        public virtual DbSet<P_CP_PINT_TISY_KIIN> P_CP_PINT_TISY_KIIN { get; set; }
        public virtual DbSet<P_CP_PINT_TISY_KIYK> P_CP_PINT_TISY_KIYK { get; set; }
        public virtual DbSet<P_CP_PINT_ZNDK> P_CP_PINT_ZNDK { get; set; }
        public virtual DbSet<P_D_PINT_KIIN_NO_JYH> P_D_PINT_KIIN_NO_JYH { get; set; }
        public virtual DbSet<P_DKJ_KMNT> P_DKJ_KMNT { get; set; }
        public virtual DbSet<P_DNKI_MSKM_COOKIES_JYH> P_DNKI_MSKM_COOKIES_JYH { get; set; }
        public virtual DbSet<P_DNKI_MSKM_SYOKAISYA_MST> P_DNKI_MSKM_SYOKAISYA_MST { get; set; }
        public virtual DbSet<P_DNKI_MSKM_UKTK_JYH> P_DNKI_MSKM_UKTK_JYH { get; set; }
        public virtual DbSet<P_EIGYO_BI_M> P_EIGYO_BI_M { get; set; }
        public virtual DbSet<P_ENTR_CD_MST> P_ENTR_CD_MST { get; set; }
        public virtual DbSet<P_ENTR_CD_TRKRRK> P_ENTR_CD_TRKRRK { get; set; }
        public virtual DbSet<P_GIFT_CAMPAIGN_KNRI> P_GIFT_CAMPAIGN_KNRI { get; set; }
        public virtual DbSet<P_GIFT_COUPON_KNRI> P_GIFT_COUPON_KNRI { get; set; }
        public virtual DbSet<P_GIFT_COUPON_LOT_KIIN> P_GIFT_COUPON_LOT_KIIN { get; set; }
        public virtual DbSet<P_GIFT_COUPON_TUSN_KIIN> P_GIFT_COUPON_TUSN_KIIN { get; set; }
        public virtual DbSet<P_IDPWD_ZDNRK> P_IDPWD_ZDNRK { get; set; }
        public virtual DbSet<P_KIIN_KHN> P_KIIN_KHN { get; set; }
        public virtual DbSet<P_KIIN_KIYK_HMTK> P_KIIN_KIYK_HMTK { get; set; }
        public virtual DbSet<P_KIIN_KIYK_HMTK_BIDN> P_KIIN_KIYK_HMTK_BIDN { get; set; }
        public virtual DbSet<P_KIIN_KIYK_HMTK_BIDN_20191120> P_KIIN_KIYK_HMTK_BIDN_20191120 { get; set; }
        public virtual DbSet<P_KIIN_KIYK_HMTK_OLD> P_KIIN_KIYK_HMTK_OLD { get; set; }
        public virtual DbSet<P_KIIN_UKTK> P_KIIN_UKTK { get; set; }
        public virtual DbSet<P_KIIN_ZYUHU_HNKU_RRK> P_KIIN_ZYUHU_HNKU_RRK { get; set; }
        public virtual DbSet<P_KNKYU_HNSU_MST> P_KNKYU_HNSU_MST { get; set; }
        public virtual DbSet<P_KNRSY_MST> P_KNRSY_MST { get; set; }
        public virtual DbSet<P_KNRSY_MTM_SYR_HMTK> P_KNRSY_MTM_SYR_HMTK { get; set; }
        public virtual DbSet<P_KR_KIIN> P_KR_KIIN { get; set; }
        public virtual DbSet<P_LINE_RNKI_JYH> P_LINE_RNKI_JYH { get; set; }
        public virtual DbSet<P_ML_HISN_MST> P_ML_HISN_MST { get; set; }
        public virtual DbSet<P_MRMG_HISN> P_MRMG_HISN { get; set; }
        public virtual DbSet<P_MTURK_KIIN> P_MTURK_KIIN { get; set; }
        public virtual DbSet<P_MTURK_KIIN_YYK> P_MTURK_KIIN_YYK { get; set; }
        public virtual DbSet<P_NNSY_CD_JYOHO> P_NNSY_CD_JYOHO { get; set; }
        public virtual DbSet<P_NNSY_MISS> P_NNSY_MISS { get; set; }
        public virtual DbSet<P_NNSY_MISS_KNRSY> P_NNSY_MISS_KNRSY { get; set; }
        public virtual DbSet<P_NNSYNNK_KIINHMTK> P_NNSYNNK_KIINHMTK { get; set; }
        public virtual DbSet<P_NYKI_RYU> P_NYKI_RYU { get; set; }
        public virtual DbSet<P_OSRS_INFO> P_OSRS_INFO { get; set; }
        public virtual DbSet<P_OSRS_KBN_GRUP_KNR> P_OSRS_KBN_GRUP_KNR { get; set; }
        public virtual DbSet<P_OSRS_KDK_KNR> P_OSRS_KDK_KNR { get; set; }
        public virtual DbSet<P_PAYPAY_ACC_JYH> P_PAYPAY_ACC_JYH { get; set; }
        public virtual DbSet<P_PINT_HYRRK_KIIN> P_PINT_HYRRK_KIIN { get; set; }
        public virtual DbSet<P_PINT_HYRRK_KIYKTNI> P_PINT_HYRRK_KIYKTNI { get; set; }
        public virtual DbSet<P_PINT_IKTSHY_YMKE> P_PINT_IKTSHY_YMKE { get; set; }
        public virtual DbSet<P_PINT_MST> P_PINT_MST { get; set; }
        public virtual DbSet<P_PINT_ZYT_MSKM> P_PINT_ZYT_MSKM { get; set; }
        public virtual DbSet<P_PWD_RRK_KNRSY> P_PWD_RRK_KNRSY { get; set; }
        public virtual DbSet<P_RYUKNRNDU_PINT> P_RYUKNRNDU_PINT { get; set; }
        public virtual DbSet<P_SHK_KIIN_UKTK> P_SHK_KIIN_UKTK { get; set; }
        public virtual DbSet<P_SIKYKG_KKTI_ML_RRK> P_SIKYKG_KKTI_ML_RRK { get; set; }
        public virtual DbSet<P_SKS_FY_MSKM> P_SKS_FY_MSKM { get; set; }
        public virtual DbSet<P_SKTI_NNSY> P_SKTI_NNSY { get; set; }
        public virtual DbSet<P_SKTI_NNSY_OLD> P_SKTI_NNSY_OLD { get; set; }
        public virtual DbSet<P_SKTI_NNSY_OLD1> P_SKTI_NNSY_OLD1 { get; set; }
        public virtual DbSet<P_SNKKIIN_MAIL_UKTK> P_SNKKIIN_MAIL_UKTK { get; set; }
        public virtual DbSet<P_SRAL_ID> P_SRAL_ID { get; set; }
        public virtual DbSet<P_SSYN_KNR> P_SSYN_KNR { get; set; }
        public virtual DbSet<P_SSYN_KNR_KNRSY> P_SSYN_KNR_KNRSY { get; set; }
        public virtual DbSet<P_SYHN_KUKN_UKTK> P_SYHN_KUKN_UKTK { get; set; }
        public virtual DbSet<P_SYOKAISYA_JYOHO> P_SYOKAISYA_JYOHO { get; set; }
        public virtual DbSet<P_SYOKAISYA_MST> P_SYOKAISYA_MST { get; set; }
        public virtual DbSet<P_TAPOINT_KKN_OTP_HK_RRK> P_TAPOINT_KKN_OTP_HK_RRK { get; set; }
        public virtual DbSet<P_TDHK_MST> P_TDHK_MST { get; set; }
        public virtual DbSet<P_TIAWS> P_TIAWS { get; set; }
        public virtual DbSet<P_TIAWS_SYBT_MST> P_TIAWS_SYBT_MST { get; set; }
        public virtual DbSet<P_TIKI> P_TIKI { get; set; }
        public virtual DbSet<P_UKTKSY_KNR> P_UKTKSY_KNR { get; set; }
        public virtual DbSet<P_YK_KIYK_MST> P_YK_KIYK_MST { get; set; }
        public virtual DbSet<P_YUBN_MST> P_YUBN_MST { get; set; }
        public virtual DbSet<WK_SIKYU_GK_STS> WK_SIKYU_GK_STS { get; set; }
        public virtual DbSet<P_LINE_SIKYKG_SYUKI_SYUKI> P_LINE_SIKYKG_SYUKI_SYUKI { get; set; }
        public virtual DbSet<VIEW_DNRYK_TTMSUTWK> VIEW_DNRYK_TTMSUTWK { get; set; }
        public virtual DbSet<VIEW_KKTZTN_SIKYU> VIEW_KKTZTN_SIKYU { get; set; }
        public virtual DbSet<VIEW_SIKYU> VIEW_SIKYU { get; set; }
        public virtual DbSet<VIEW_SIKYU_KNR> VIEW_SIKYU_KNR { get; set; }
        public virtual DbSet<VIEW_TTMS> VIEW_TTMS { get; set; }
        public virtual DbSet<VIEW_TYUTI> VIEW_TYUTI { get; set; }
    
        public virtual int P_KIIN_KIYK_HMTK_UPDATE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_KIIN_KIYK_HMTK_UPDATE");
        }
    }
}
