//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_SIKYU_KNR
    {
        public string SIKYU_KNR_NO { get; set; }
        public string SIKYU_YM { get; set; }
        public string URAG_YM { get; set; }
        public string SKTI_NO { get; set; }
        public string SIKYU_TIMNG_KBN { get; set; }
        public string SIKYU_KKTI_YMD { get; set; }
        public string SHH_KBN { get; set; }
        public string KZHK_YMD_IT { get; set; }
        public string KZHK_YMD_N { get; set; }
        public string KZHK_YMD_SN { get; set; }
        public string KZHK_SKYZT_KBN { get; set; }
        public string RNR_SKZY_FLG { get; set; }
    }
}
