//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_TYUTI
    {
        public string TYUTI_KNR_NO { get; set; }
        public string SIKYU_KNR_NO { get; set; }
        public string SY_KIYK_NO { get; set; }
        public string TYYM { get; set; }
        public string TYUTI_HKU_KBN { get; set; }
        public Nullable<decimal> HKU_KISU { get; set; }
        public string HISN_SIKYU_KBN { get; set; }
        public string URAG_YM { get; set; }
        public string SKTI_NO { get; set; }
        public Nullable<decimal> TYUTI_GK { get; set; }
        public Nullable<decimal> NYUKN_GK { get; set; }
        public Nullable<decimal> SYHZ { get; set; }
        public string KSKIB_SYBT { get; set; }
        public string KSKIB { get; set; }
        public string TIRI_KYM_H { get; set; }
        public string TIRI_KKTI_YMD { get; set; }
        public string KYM_H { get; set; }
        public string KSN_YMD { get; set; }
        public string TYYM_NTZHNBYU { get; set; }
        public string KKTI_YMD { get; set; }
        public string RYUKN_TISI_YMD { get; set; }
        public string YKGT_KRKS_KBN { get; set; }
        public string YUKU_TTMS_AR_FLG { get; set; }
        public string SISNHYU_AR_FLG { get; set; }
        public string KSI_NO { get; set; }
        public string KKTIZM_FLG { get; set; }
        public string SU_NO { get; set; }
        public string SEUS_NO { get; set; }
        public Nullable<decimal> KUSN_KNTR { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
