//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_SIKYU
    {
        public string SIKYU_KNR_NO { get; set; }
        public string SIKYU_YM { get; set; }
        public string URAG_YM { get; set; }
        public string SKTI_NO { get; set; }
        public string DKYS_NO { get; set; }
        public string SKKT_KBN { get; set; }
        public string SIKYU_HKU_KBN { get; set; }
        public string SIKYU_KISU { get; set; }
        public Nullable<decimal> SIKYU_GK { get; set; }
        public Nullable<decimal> SYHZ { get; set; }
        public Nullable<decimal> KRKS_NYUKN_GK { get; set; }
        public Nullable<decimal> NYUKN_GK { get; set; }
        public string HRIKM_RNBN { get; set; }
        public string SHH_KBN { get; set; }
        public string KSKIB_SYBT { get; set; }
        public string KSKIB { get; set; }
        public string TIRI_KKTI_YMD { get; set; }
        public string KYM_H { get; set; }
        public string YKGT_KRKS_FLG { get; set; }
        public string SEUS_AR_FLG { get; set; }
        public string MIG_NO_AR_FLG { get; set; }
        public string MIG_NO { get; set; }
        public Nullable<decimal> YUKU_TYKS { get; set; }
        public Nullable<decimal> MKU_TYKS { get; set; }
        public Nullable<decimal> SIKYU_KNTR { get; set; }
        public string KKTIZM_FLG { get; set; }
        public Nullable<decimal> SISN_NYUKN_GK { get; set; }
        public string SISN_NYUKN_HUHU_KBN { get; set; }
        public Nullable<decimal> KUSN_KNTR { get; set; }
        public string RNR_SKZY_FLG { get; set; }
        public Nullable<System.DateTime> TURK_TIMSTNP { get; set; }
        public Nullable<System.DateTime> KUSN_TIMSTNP { get; set; }
    }
}
