//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDotNetWebFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class WK_SIKYU_GK_STS
    {
        public string KIIN_ID { get; set; }
        public string SIKYU_YM { get; set; }
        public string SBS_SYBT { get; set; }
        public string KIYK_NO { get; set; }
        public string KIYK_SYBT { get; set; }
        public string KIYK_KNG_H_OLD { get; set; }
        public string KIYK_KNG_H { get; set; }
        public string KIYK_SYRY_YMD { get; set; }
        public Nullable<decimal> GK { get; set; }
        public System.DateTime TURK_TIMSTNP { get; set; }
    }
}
